- hosts: all
  gather_facts: true
  roles:
    - update_system
    - install_xrootd
    - setup_data_directory
    - cert_setup
    - configure_xrootd
    - role: rucio
      when: ansible_facts["distribution"] == "Rocky" and rucio == true
    - tests
