- hosts: all
  tags: update_system
  any_errors_fatal: true
  gather_facts: true
  roles:
    - update_system

- hosts: all
  tags: hardening
  any_errors_fatal: true
  gather_facts: true
  collections:
    - devsec.hardening
  roles:
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening
  become: true

- hosts: all
  tags: manage_users
  any_errors_fatal: true
  gather_facts: true
  vars_files:
    - group_vars/all/users.yml
  roles:
    - manage_users
  become: true

- hosts: all
  tags: install_xrootd
  any_errors_fatal: true
  gather_facts: true
  roles:
    - install_xrootd
    - setup_data_directory
    - cert_setup
    - configure_xrootd
    - role: rucio
      when: ansible_facts["distribution"] == "Rocky" and rucio == true
    - tests
