ssh_local_access_cidr: 192.168.100.0/24
wcdc_dirac_subnet: 192.84.5.0/27
wcdc_dirac_gateway: 192.84.5.30
wcdc_dirac_zone: wcdc-dirac
wcdc_dirac_xrootd_port: 1094
wcdc_dirac_interface: "eth1"
iris_interface: "eth2"
uksrc_interface: "eth0"
wcdc_dirac_ip: 192.84.5.20
uksrc_zone: uksrc
