- name: Install Ceph centos-release-ceph-squid
  ansible.builtin.dnf:
    name:
      - centos-release-ceph-squid
    state: present
  become: true

- name: Install Ceph other packages
  ansible.builtin.dnf:
    name:
      - ceph-common
      - ceph-fuse
    state: present
  become: true

- name: Create the ceph config file
  ansible.builtin.template:
    src: ceph.conf.j2
    dest: /etc/ceph/ceph.conf
    mode: '0600'
    owner: root
    group: root
  become: true

- name: Create the manila share ceph secret
  ansible.builtin.template:
    src: ceph-keyring.j2
    dest: "/etc/ceph/ceph.client.{{ manila_access_to }}.keyring"
    mode: '0600'
    owner: root
    group: root
  become: true

- name: Add manila share to fstab
  ansible.posix.mount:
    path: /skadata
    src: "{{ manila_host }}:{{ manila_share_export }}"
    fstype: ceph
    opts: "name={{ manila_access_to }},{{ manila_share_mnt_opts }}"
    state: present
  become: true

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart systemd remote-fs.target
  ansible.builtin.systemd:
    name: remote-fs.target
    state: restarted
  become: true
