- name: Create {{ data_path }}
  ansible.builtin.file:
    path: "{{ data_path }}"
    state: directory
    mode: '0755'
    owner: xrootd
    group: xrootd
  become: true

- name: Configure ceph storage
  import_tasks: ceph.yml
  when: storage_type == "ceph"
  become: true

- name: Configure volume storage
  import_tasks: volume.yml
  when: storage_type == "volume"
  become: true
