- name: Check {{ data_path }} exists
  ansible.builtin.stat:
    path: "{{ data_path }}"
  register: validate_data_path

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: validate_data_path
    verbosity: 1

- name: Create {{ data_path }}
  ansible.builtin.file:
    path: "{{ data_path }}"
    state: directory
    mode: '0755'
    owner: xrootd
    group: xrootd
  when: validate_data_path.stat.exists is defined and not validate_data_path.stat.exists
  become: true

- name: Configure ceph storage
  import_tasks: ceph.yml
  when: storage_type == "ceph"
  become: true

- name: Configure volume storage
  import_tasks: volume.yml
  when: storage_type == "volume"
  become: true
