- hosts: all
  gather_facts: true
  roles:
    # - update_system
    # - { role: install_xrootd_ubuntu, when: ansible_distribution == "Ubuntu" }
    # - { role: install_xrootd_rocky, when: ansible_distribution == "Rocky" }
    # - setup_data_directory
    - cert_setup
    - configure_xrootd
    - { role: rucio, when: ansible_distribution == "Rocky" and rucio == true}
    - tests

