- name: Update apt packages
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
    autoremove: yes
    autoclean: yes
  become: true
  when: ansible_distribution == 'Ubuntu'
  register: result
  until: result is not failed
  retries: 5
  delay: 30

- name: Update dnf packages
  ansible.builtin.dnf:
    update_cache: yes
    autoremove: yes
  become: true
  when: ansible_distribution == 'Rocky'
  register: result
  until: result is not failed
  retries: 5
  delay: 30