name: Harbor Labeler Docker Image CI

on:
    pull_request:
        types:
            - opened
            - synchronize
            - ready_for_review
            - reopened
        branches:
            - main
        paths:
            - "canfar-replication/**"
            - ".github/workflows/harbor_labeler_ci.yaml"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Set image tag
              id: vars
              run: echo "tag=$(date +%s)" >> "$GITHUB_OUTPUT"

            - name: Build the Harbor Labeler Docker image
              uses: docker/build-push-action@v6
              with:
                  context: ./canfar-replication/python
                  file: ./canfar-replication/python/Dockerfile
                  platforms: linux/amd64,linux/arm64
                  push: false
                  tags: |
                      harbor-labeler:${{ steps.vars.outputs.tag }}
